//! The catalogue entries for the desktop primitives.

use crate::names::methods;

use super::{Family, Member, entry};

/// The desktop members, in [`crate::names::METHODS`] order.
pub(super) const DESKTOP: &[Member] = &[
    entry(
        methods::SNAPSHOT,
        Family::Desktop,
        "Walks an application's accessibility tree and allocates a ref per element.",
        false,
    ),
    entry(
        methods::FIND,
        Family::Desktop,
        "Returns the elements matching a role, name, or text query.",
        false,
    ),
    entry(
        methods::GET,
        Family::Desktop,
        "Reads one property of one ref.",
        false,
    ),
    entry(
        methods::IS,
        Family::Desktop,
        "Tests one boolean state of one ref.",
        false,
    ),
    entry(
        methods::SCREENSHOT,
        Family::Desktop,
        "Captures an application, window, or display as an image.",
        false,
    ),
    entry(
        methods::CLICK,
        Family::Desktop,
        "Clicks a ref through its accessibility action.",
        false,
    ),
    entry(
        methods::DOUBLE_CLICK,
        Family::Desktop,
        "Double-clicks a ref.",
        false,
    ),
    entry(
        methods::TRIPLE_CLICK,
        Family::Desktop,
        "Triple-clicks a ref.",
        false,
    ),
    entry(
        methods::RIGHT_CLICK,
        Family::Desktop,
        "Right-clicks a ref, opening its context menu.",
        false,
    ),
    entry(
        methods::TYPE,
        Family::Desktop,
        "Types text into a ref.",
        false,
    ),
    entry(
        methods::SET_VALUE,
        Family::Desktop,
        "Replaces a ref's value in one step.",
        false,
    ),
    entry(
        methods::CLEAR,
        Family::Desktop,
        "Empties a ref's value.",
        false,
    ),
    entry(
        methods::FOCUS,
        Family::Desktop,
        "Gives a ref keyboard focus.",
        false,
    ),
    entry(
        methods::SELECT,
        Family::Desktop,
        "Selects an option within a ref.",
        false,
    ),
    entry(
        methods::TOGGLE,
        Family::Desktop,
        "Toggles a checkable ref.",
        false,
    ),
    entry(
        methods::CHECK,
        Family::Desktop,
        "Checks a checkable ref.",
        false,
    ),
    entry(
        methods::UNCHECK,
        Family::Desktop,
        "Unchecks a checkable ref.",
        false,
    ),
    entry(
        methods::EXPAND,
        Family::Desktop,
        "Expands an expandable ref.",
        false,
    ),
    entry(
        methods::COLLAPSE,
        Family::Desktop,
        "Collapses an expandable ref.",
        false,
    ),
    entry(
        methods::SCROLL,
        Family::Desktop,
        "Scrolls a scrollable ref.",
        false,
    ),
    entry(
        methods::SCROLL_TO,
        Family::Desktop,
        "Scrolls a ref into view.",
        false,
    ),
    entry(
        methods::PRESS,
        Family::Desktop,
        "Presses a key combination.",
        false,
    ),
    entry(
        methods::KEY_DOWN,
        Family::Desktop,
        "Reserved for a stateful daemon; fails closed.",
        false,
    ),
    entry(
        methods::KEY_UP,
        Family::Desktop,
        "Reserved for a stateful daemon; fails closed.",
        false,
    ),
    entry(
        methods::HOVER,
        Family::Desktop,
        "Moves the cursor over a ref or a point.",
        false,
    ),
    entry(
        methods::DRAG,
        Family::Desktop,
        "Drags between two endpoints.",
        false,
    ),
    entry(
        methods::MOUSE_MOVE,
        Family::Desktop,
        "Moves the cursor to a point.",
        false,
    ),
    entry(
        methods::MOUSE_CLICK,
        Family::Desktop,
        "Clicks at a point.",
        false,
    ),
    entry(
        methods::MOUSE_DOWN,
        Family::Desktop,
        "Reserved for a stateful daemon; fails closed.",
        false,
    ),
    entry(
        methods::MOUSE_UP,
        Family::Desktop,
        "Reserved for a stateful daemon; fails closed.",
        false,
    ),
    entry(
        methods::MOUSE_WHEEL,
        Family::Desktop,
        "Scrolls the wheel at a point.",
        false,
    ),
    entry(
        methods::LAUNCH,
        Family::Desktop,
        "Starts or attaches to an application.",
        false,
    ),
    entry(
        methods::CLOSE_APP,
        Family::Desktop,
        "Quits or terminates an application.",
        false,
    ),
    entry(
        methods::LIST_APPS,
        Family::Desktop,
        "Lists running applications.",
        false,
    ),
    entry(
        methods::LIST_WINDOWS,
        Family::Desktop,
        "Lists windows.",
        false,
    ),
    entry(
        methods::LIST_DISPLAYS,
        Family::Desktop,
        "Lists displays.",
        false,
    ),
    entry(
        methods::LIST_SURFACES,
        Family::Desktop,
        "Lists the surfaces an application currently exposes.",
        false,
    ),
    entry(
        methods::FOCUS_WINDOW,
        Family::Desktop,
        "Brings a window forward.",
        false,
    ),
    entry(
        methods::RESIZE_WINDOW,
        Family::Desktop,
        "Resizes a window.",
        false,
    ),
    entry(
        methods::MOVE_WINDOW,
        Family::Desktop,
        "Moves a window.",
        false,
    ),
    entry(
        methods::MINIMIZE,
        Family::Desktop,
        "Minimizes a window.",
        false,
    ),
    entry(
        methods::MAXIMIZE,
        Family::Desktop,
        "Maximizes a window.",
        false,
    ),
    entry(
        methods::RESTORE,
        Family::Desktop,
        "Restores a minimized or maximized window.",
        false,
    ),
    entry(
        methods::CLIPBOARD_GET,
        Family::Desktop,
        "Reads the pasteboard.",
        false,
    ),
    entry(
        methods::CLIPBOARD_SET,
        Family::Desktop,
        "Writes the pasteboard.",
        false,
    ),
    entry(
        methods::CLIPBOARD_CLEAR,
        Family::Desktop,
        "Empties the pasteboard.",
        false,
    ),
    entry(
        methods::LIST_NOTIFICATIONS,
        Family::Desktop,
        "Lists notification-centre entries.",
        false,
    ),
    entry(
        methods::NOTIFICATION_ACTION,
        Family::Desktop,
        "Invokes an action on a notification.",
        false,
    ),
    entry(
        methods::DISMISS_NOTIFICATION,
        Family::Desktop,
        "Dismisses one notification.",
        false,
    ),
    entry(
        methods::DISMISS_ALL_NOTIFICATIONS,
        Family::Desktop,
        "Dismisses every notification, optionally for one application.",
        false,
    ),
    entry(
        methods::WAIT,
        Family::Desktop,
        "Blocks until a condition holds or the timeout expires.",
        false,
    ),
    entry(
        methods::VERSION,
        Family::Desktop,
        "Reports the engine version and target.",
        false,
    ),
    entry(
        methods::STATUS,
        Family::Desktop,
        "Reports permissions, the active session, and the latest snapshot.",
        false,
    ),
    entry(
        methods::PERMISSIONS,
        Family::Desktop,
        "Reports, and optionally prompts for, the permissions automation needs.",
        false,
    ),
    entry(
        crate::names::accessibility::ACCESSIBILITY_PERMISSIONS,
        Family::Desktop,
        "Reads native accessibility, input-monitoring and microphone permission states.",
        false,
    ),
    entry(
        crate::names::accessibility::ACCESSIBILITY_REQUEST_PERMISSION,
        Family::Desktop,
        "Requests one native permission and returns current states.",
        false,
    ),
    entry(
        crate::names::accessibility::ACCESSIBILITY_FOCUS,
        Family::Desktop,
        "Reads the focused text context inside the computer module.",
        true,
    ),
    entry(
        crate::names::accessibility::ACCESSIBILITY_VALIDATE_TARGET,
        Family::Desktop,
        "Validates the captured application, role and bounds.",
        true,
    ),
    entry(
        crate::names::accessibility::ACCESSIBILITY_PASTE,
        Family::Desktop,
        "Validates captured focus and inserts authorized text.",
        true,
    ),
    entry(
        crate::names::accessibility::GLOBE_START,
        Family::Desktop,
        "Starts the module-owned Globe listener and returns its lease.",
        false,
    ),
    entry(
        crate::names::accessibility::GLOBE_POLL,
        Family::Desktop,
        "Drains a bounded ordered batch for a Globe listener lease.",
        false,
    ),
    entry(
        crate::names::accessibility::GLOBE_READ,
        Family::Desktop,
        "Reads an acknowledged replayable Globe batch.",
        false,
    ),
    entry(
        crate::names::accessibility::GLOBE_SHUTDOWN,
        Family::Desktop,
        "Joins terminal native listener cleanup.",
        false,
    ),
    entry(
        crate::names::accessibility::GLOBE_STOP,
        Family::Desktop,
        "Stops and releases a Globe listener lease.",
        false,
    ),
];
