//! The served interface: one `async fn` per member of the contract.
//!
//! Every desktop method has the same body — hand a copy of the engine to a
//! blocking thread and return the envelope it produces — and every browser
//! method the same other body — await the shared [`Browser`] and wrap its
//! result in that same envelope — so the file is long and uninteresting on
//! purpose. What matters is that the order below is the order
//! of [`tinycomputer_bus::names::METHODS`];
//! `tinybus_module_tests/manifest_tests.rs` asserts the generated dispatch
//! table against that list, so a member added in one place and not the other
//! fails the build.
//!
//! The methods cannot be generated by a macro: `#[tinybus::interface]` reads
//! the `impl` block's items to build its dispatch table, and a `macro_rules!`
//! invocation inside that block is still unexpanded when it does. Writing them
//! out is what lets the macro see them.

mod accessibility;
mod browser;
mod service;

use browser::browser_reply;
pub(super) use browser::observing_reply;

pub(super) use service::desktop_availability;
#[cfg(test)]
pub(super) use service::sweep_every;

use tinybus::Result as TinyBusResult;
use tinycomputer_bus::{
    ClipboardGetRequest, ClipboardSetRequest, CloseAppRequest, DesktopResponse,
    DismissAllNotificationsRequest, DismissNotificationRequest, DragRequest, FindRequest,
    FocusWindowRequest, GetRequest, HoldKeyRequest, HoldMouseRequest, HoverRequest, IsRequest,
    LaunchRequest, ListAppsRequest, ListNotificationsRequest, ListSurfacesRequest,
    ListWindowsRequest, MouseClickRequest, MouseMoveRequest, MouseWheelRequest, MoveWindowRequest,
    NotificationActionRequest, PermissionsRequest, PressRequest, RefRequest, ResizeWindowRequest,
    ResolveIntentRequest, RunFlowRequest, RunGoalRequest, ScreenshotRequest, ScrollRequest,
    SelectRequest, SetValueRequest, SnapshotRequest, TypeRequest, ValidateFlowRequest, WaitRequest,
    WindowRequest,
};

use std::sync::Arc;

use tinycomputer_bus::agent::{
    AgentResponse, AwaitTaskRequest, Capabilities, ContinueTaskRequest, PlanTaskRequest,
    StartTaskRequest, SurfaceAvailability, SurfaceKind, TaskPlan, TaskRef, TaskReport,
    TaskReportRequest, TaskView,
};

use super::runner::jev_not_configured;
use crate::Desktop;
use tinycomputer_browser::{
    Action, Browser, DownloadWaitRequest, EvaluateRequest, NavigateRequest, OutputRequest,
    ReadOutputRequest, ReadRequest, ScreenshotRequest as BrowserScreenshotRequest, SessionOptions,
    SessionRef, SessionRequest, SnapshotRequest as BrowserSnapshotRequest,
};
use tinycomputer_engine as agentic;

/// The object served at [`tinycomputer_bus::names::OBJECT_PATH`].
///
/// It holds the configured engines and nothing else. Cloning it is cheap, which
/// is what lets every member hand a copy to a blocking thread instead of
/// borrowing one across an `await`.
///
/// The [`Browser`] is the one the task runner opens its sessions on, so the
/// browser members see a task's session and can read the screenshots its
/// views name, and one session limit covers both.
#[derive(Debug, Clone)]
pub(crate) struct DesktopService {
    desktop: Desktop,
    jev: Option<agentic::JevRuntime>,
    pub(super) tasks: Arc<agentic::Tasks>,
    browser: Arc<Browser>,
    /// The configured `browser` settings, filled into a
    /// `BrowserOpenSession` wherever the caller left them unset.
    browser_defaults: crate::tinybus_module::config::BrowserDefaults,
    accessibility: Arc<accessibility::Access>,
}

#[tinybus::interface(name = "ai.tinyhumans.tinycomputer.Desktop")]
impl DesktopService {
    /// Resolves one natural-language intent against the current screen.
    #[tinybus(confidential)]
    async fn resolve_intent(
        &self,
        request: ResolveIntentRequest,
    ) -> TinyBusResult<DesktopResponse> {
        let Some(runtime) = self.jev_runtime() else {
            return Ok(jev_not_configured("resolve-intent"));
        };
        Ok(agentic::resolve_intent(self.desktop.clone(), runtime, request).await)
    }

    /// Runs a bounded Jev observe-decide-act loop.
    #[tinybus(confidential)]
    async fn run_goal(&self, request: RunGoalRequest) -> TinyBusResult<DesktopResponse> {
        let Some(runtime) = self.jev_runtime() else {
            return Ok(jev_not_configured("run-goal"));
        };
        Ok(agentic::run_goal(self.desktop.clone(), runtime, request).await)
    }

    /// Runs a high-level intent flow with Jev decision loops.
    #[tinybus(confidential)]
    async fn run_flow(&self, request: RunFlowRequest) -> TinyBusResult<DesktopResponse> {
        let Some(runtime) = self.jev_runtime() else {
            return Ok(jev_not_configured("run-flow"));
        };
        Ok(agentic::run_flow(self.desktop.clone(), runtime, request).await)
    }

    /// Checks a flow without touching the desktop or Jev.
    async fn validate_flow(&self, request: ValidateFlowRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |_| agentic::validate_flow(&request)).await
    }

    /// Returns the flow authoring guide as prompt text.
    async fn flow_guide(&self) -> TinyBusResult<DesktopResponse> {
        self.run(|_| agentic::flow_guide()).await
    }

    /// Everything a model needs to drive the task members, in one reply.
    async fn describe(&self) -> TinyBusResult<Capabilities> {
        let permissions = self
            .run(|desktop| desktop.permissions(PermissionsRequest::default()))
            .await?;
        Ok(agentic::capabilities(
            vec![
                desktop_availability(&permissions),
                SurfaceAvailability {
                    kind: SurfaceKind::Browser,
                    available: true,
                    reason: None,
                },
            ],
            self.jev.as_ref().map(agentic::JevRuntime::configuration),
            &self.tasks,
        ))
    }

    /// Drafts a flow for a plain-language task; needs a planner.
    async fn plan_task(&self, request: PlanTaskRequest) -> TinyBusResult<AgentResponse<TaskPlan>> {
        Ok(self.tasks.plan(&request).await)
    }

    /// Starts a task and returns at once with its first view.
    #[tinybus(confidential)]
    async fn start_task(
        &self,
        request: StartTaskRequest,
    ) -> TinyBusResult<AgentResponse<TaskView>> {
        self.on_tasks(move |tasks| tasks.start(&request)).await
    }

    /// Waits until a task needs something, finishes, or the timeout passes.
    async fn await_task(
        &self,
        request: AwaitTaskRequest,
    ) -> TinyBusResult<AgentResponse<TaskView>> {
        Ok(self.tasks.await_task(request).await)
    }

    /// Answers what a paused task asked for, and resumes it.
    #[tinybus(confidential)]
    async fn continue_task(
        &self,
        request: ContinueTaskRequest,
    ) -> TinyBusResult<AgentResponse<TaskView>> {
        self.on_tasks(move |tasks| tasks.continue_task(request))
            .await
    }

    /// Stops a task.
    async fn cancel_task(&self, request: TaskRef) -> TinyBusResult<AgentResponse<TaskView>> {
        self.on_tasks(move |tasks| tasks.cancel(&request.id)).await
    }

    /// Everything a task did.
    #[tinybus(confidential)]
    async fn task_report(
        &self,
        request: TaskReportRequest,
    ) -> TinyBusResult<AgentResponse<TaskReport>> {
        self.on_tasks(move |tasks| tasks.report_for(&request)).await
    }

    /// The tasks this module holds, newest first.
    async fn list_tasks(&self) -> TinyBusResult<AgentResponse<Vec<TaskView>>> {
        self.on_tasks(agentic::Tasks::list).await
    }

    /// Walks an accessibility tree and allocates a ref per element.
    async fn snapshot(&self, request: SnapshotRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.snapshot(request)).await
    }

    /// Returns the elements matching a query.
    async fn find(&self, request: FindRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.find(request)).await
    }

    /// Reads one property of one ref.
    async fn get(&self, request: GetRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.get(request)).await
    }

    /// Tests one boolean state of one ref.
    async fn is(&self, request: IsRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.is(request)).await
    }

    /// Captures an application, window, or display as an image.
    async fn screenshot(&self, request: ScreenshotRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.screenshot(request)).await
    }

    /// Clicks a ref through its accessibility action.
    async fn click(&self, request: RefRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.click(request)).await
    }

    /// Double-clicks a ref.
    async fn double_click(&self, request: RefRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.double_click(request)).await
    }

    /// Triple-clicks a ref.
    async fn triple_click(&self, request: RefRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.triple_click(request)).await
    }

    /// Right-clicks a ref, opening its context menu.
    async fn right_click(&self, request: RefRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.right_click(request)).await
    }

    /// Types text into a ref.
    #[tinybus(name = "Type")]
    async fn type_text(&self, request: TypeRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.type_text(request)).await
    }

    /// Replaces a ref's value in one step.
    async fn set_value(&self, request: SetValueRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.set_value(request)).await
    }

    /// Empties a ref's value.
    async fn clear(&self, request: RefRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.clear(request)).await
    }

    /// Gives a ref keyboard focus.
    async fn focus(&self, request: RefRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.focus(request)).await
    }

    /// Selects an option within a ref.
    async fn select(&self, request: SelectRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.select(request)).await
    }

    /// Toggles a checkable ref.
    async fn toggle(&self, request: RefRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.toggle(request)).await
    }

    /// Checks a checkable ref.
    async fn check(&self, request: RefRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.check(request)).await
    }

    /// Unchecks a checkable ref.
    async fn uncheck(&self, request: RefRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.uncheck(request)).await
    }

    /// Expands an expandable ref.
    async fn expand(&self, request: RefRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.expand(request)).await
    }

    /// Collapses an expandable ref.
    async fn collapse(&self, request: RefRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.collapse(request)).await
    }

    /// Scrolls a scrollable ref.
    async fn scroll(&self, request: ScrollRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.scroll(request)).await
    }

    /// Scrolls a ref into view.
    async fn scroll_to(&self, request: RefRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.scroll_to(request)).await
    }

    /// Presses a key combination.
    async fn press(&self, request: PressRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.press(request)).await
    }

    /// Reserved for a stateful daemon; validates and then fails closed.
    async fn key_down(&self, request: HoldKeyRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.key_down(request)).await
    }

    /// Reserved for a stateful daemon; validates and then fails closed.
    async fn key_up(&self, request: HoldKeyRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.key_up(request)).await
    }

    /// Moves the cursor over a ref or a point.
    async fn hover(&self, request: HoverRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.hover(request)).await
    }

    /// Drags between two endpoints.
    async fn drag(&self, request: DragRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.drag(request)).await
    }

    /// Moves the cursor to a point.
    async fn mouse_move(&self, request: MouseMoveRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.mouse_move(request)).await
    }

    /// Clicks at a point.
    async fn mouse_click(&self, request: MouseClickRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.mouse_click(request)).await
    }

    /// Reserved for a stateful daemon; validates and then fails closed.
    async fn mouse_down(&self, request: HoldMouseRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.mouse_down(request)).await
    }

    /// Reserved for a stateful daemon; validates and then fails closed.
    async fn mouse_up(&self, request: HoldMouseRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.mouse_up(request)).await
    }

    /// Scrolls the wheel at a point.
    async fn mouse_wheel(&self, request: MouseWheelRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.mouse_wheel(request)).await
    }

    /// Starts an application, or attaches to a running one.
    async fn launch(&self, request: LaunchRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.launch(request)).await
    }

    /// Quits or terminates an application.
    async fn close_app(&self, request: CloseAppRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.close_app(request)).await
    }

    /// Lists running applications.
    async fn list_apps(&self, request: ListAppsRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.list_apps(request)).await
    }

    /// Lists windows.
    async fn list_windows(&self, request: ListWindowsRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.list_windows(request)).await
    }

    /// Lists displays.
    async fn list_displays(&self) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.list_displays()).await
    }

    /// Lists the surfaces an application currently exposes.
    async fn list_surfaces(&self, request: ListSurfacesRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.list_surfaces(request))
            .await
    }

    /// Brings a window forward.
    async fn focus_window(&self, request: FocusWindowRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.focus_window(request)).await
    }

    /// Resizes a window.
    async fn resize_window(&self, request: ResizeWindowRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.resize_window(request))
            .await
    }

    /// Moves a window's origin.
    async fn move_window(&self, request: MoveWindowRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.move_window(request)).await
    }

    /// Minimizes a window.
    async fn minimize(&self, request: WindowRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.minimize(request)).await
    }

    /// Maximizes a window.
    async fn maximize(&self, request: WindowRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.maximize(request)).await
    }

    /// Restores a minimized or maximized window.
    async fn restore(&self, request: WindowRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.restore(request)).await
    }

    /// Reads the pasteboard.
    async fn clipboard_get(&self, request: ClipboardGetRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.clipboard_get(request))
            .await
    }

    /// Writes the pasteboard.
    async fn clipboard_set(&self, request: ClipboardSetRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.clipboard_set(request))
            .await
    }

    /// Empties the pasteboard.
    async fn clipboard_clear(&self) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.clipboard_clear()).await
    }

    /// Lists notification-centre entries.
    async fn list_notifications(
        &self,
        request: ListNotificationsRequest,
    ) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.list_notifications(request))
            .await
    }

    /// Invokes an action on a notification.
    async fn notification_action(
        &self,
        request: NotificationActionRequest,
    ) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.notification_action(request))
            .await
    }

    /// Dismisses one notification.
    async fn dismiss_notification(
        &self,
        request: DismissNotificationRequest,
    ) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.dismiss_notification(request))
            .await
    }

    /// Dismisses every notification, optionally scoped to one application.
    async fn dismiss_all_notifications(
        &self,
        request: DismissAllNotificationsRequest,
    ) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.dismiss_all_notifications(request))
            .await
    }

    /// Blocks until a condition holds or the timeout expires.
    async fn wait(&self, request: WaitRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.wait(request)).await
    }

    /// Reports the engine version and target.
    async fn version(&self) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.version()).await
    }

    /// Reports permissions, the active session, and the latest snapshot.
    async fn status(&self) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.status()).await
    }

    /// Reports, and optionally prompts for, the permissions automation needs.
    async fn permissions(&self, request: PermissionsRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.permissions(request)).await
    }

    /// Native accessibility permissions through module-owned resources.
    async fn accessibility_permissions(&self) -> TinyBusResult<DesktopResponse> {
        accessibility::run(
            Arc::clone(&self.accessibility),
            "accessibility-permissions",
            move |a| Ok(a.permissions()),
        )
        .await
    }

    /// Native accessibility request permission through module-owned resources.
    async fn accessibility_request_permission(
        &self,
        kind: tinycomputer_bus::accessibility::PermissionKind,
    ) -> TinyBusResult<DesktopResponse> {
        accessibility::run(
            Arc::clone(&self.accessibility),
            "accessibility-request-permission",
            move |a| Ok(a.request_permission(kind)),
        )
        .await
    }

    /// Native accessibility focus through module-owned resources.
    #[tinybus(confidential)]
    async fn accessibility_focus(
        &self,
        query: tinycomputer_bus::accessibility::FocusQuery,
    ) -> TinyBusResult<DesktopResponse> {
        accessibility::run(
            Arc::clone(&self.accessibility),
            "accessibility-focus",
            move |a| a.focus(query),
        )
        .await
    }

    /// Native accessibility validate target through module-owned resources.
    #[tinybus(confidential)]
    async fn accessibility_validate_target(
        &self,
        target: tinycomputer_bus::accessibility::FocusTarget,
    ) -> TinyBusResult<DesktopResponse> {
        accessibility::run(
            Arc::clone(&self.accessibility),
            "accessibility-validate-target",
            move |a| a.validate(&target),
        )
        .await
    }

    /// Native accessibility paste through module-owned resources.
    #[tinybus(confidential)]
    async fn accessibility_paste(
        &self,
        request: tinycomputer_bus::accessibility::PasteRequest,
    ) -> TinyBusResult<DesktopResponse> {
        accessibility::run(
            Arc::clone(&self.accessibility),
            "accessibility-paste",
            move |a| a.paste(request),
        )
        .await
    }

    /// Native globe start through module-owned resources.
    async fn globe_start(&self) -> TinyBusResult<DesktopResponse> {
        accessibility::run(Arc::clone(&self.accessibility), "globe-start", move |a| {
            a.start()
        })
        .await
    }

    /// Native globe poll through module-owned resources.
    async fn globe_poll(
        &self,
        handle: tinycomputer_bus::accessibility::GlobeHandle,
    ) -> TinyBusResult<DesktopResponse> {
        accessibility::run(Arc::clone(&self.accessibility), "globe-poll", move |a| {
            a.poll(&handle)
        })
        .await
    }

    /// Read a replayable acknowledged native Globe batch.
    async fn globe_read(
        &self,
        request: tinycomputer_bus::accessibility::GlobeRead,
    ) -> TinyBusResult<DesktopResponse> {
        accessibility::run(Arc::clone(&self.accessibility), "globe-read", move |a| {
            a.read(&request)
        })
        .await
    }

    /// Terminal joined listener cleanup before unloading the module.
    async fn globe_shutdown(&self) -> TinyBusResult<DesktopResponse> {
        // Close admission before scheduling the blocking cleanup barrier.
        self.accessibility.close_admission();
        accessibility::run(
            Arc::clone(&self.accessibility),
            "globe-shutdown",
            accessibility::Access::shutdown,
        )
        .await
    }

    /// Native globe stop through module-owned resources.
    async fn globe_stop(
        &self,
        handle: tinycomputer_bus::accessibility::GlobeHandle,
    ) -> TinyBusResult<DesktopResponse> {
        accessibility::run(Arc::clone(&self.accessibility), "globe-stop", move |a| {
            a.stop(&handle)
        })
        .await
    }

    /// Launches or attaches a browser and returns its session.
    async fn browser_open_session(
        &self,
        options: SessionOptions,
    ) -> TinyBusResult<DesktopResponse> {
        Ok(observing_reply(
            "browser-open-session",
            self.browser
                .open_session(self.browser_defaults.apply(options))
                .await,
        ))
    }

    /// Closes a session and everything it owns.
    async fn browser_close_session(&self, request: SessionRef) -> TinyBusResult<DesktopResponse> {
        Ok(browser_reply(
            "browser-close-session",
            self.browser
                .close_session(&request.session)
                .await
                .map(|()| serde_json::json!({"session": request.session, "closed": true})),
        ))
    }

    /// Lists the browser sessions this module holds.
    async fn browser_list_sessions(&self) -> TinyBusResult<DesktopResponse> {
        Ok(browser_reply(
            "browser-list-sessions",
            self.browser.list_sessions().await,
        ))
    }

    /// Navigates a session's active page.
    async fn browser_navigate(
        &self,
        request: SessionRequest<NavigateRequest>,
    ) -> TinyBusResult<DesktopResponse> {
        Ok(browser_reply(
            "browser-navigate",
            self.browser
                .navigate(&request.session, request.request)
                .await,
        ))
    }

    /// Captures the active page's accessibility tree with element refs.
    async fn browser_snapshot(
        &self,
        request: SessionRequest<BrowserSnapshotRequest>,
    ) -> TinyBusResult<DesktopResponse> {
        Ok(observing_reply(
            "browser-snapshot",
            self.browser
                .snapshot(&request.session, request.request)
                .await,
        ))
    }

    /// Performs one interaction on the active page.
    async fn browser_perform(
        &self,
        request: SessionRequest<Action>,
    ) -> TinyBusResult<DesktopResponse> {
        Ok(browser_reply(
            "browser-perform",
            self.browser
                .perform(&request.session, request.request)
                .await,
        ))
    }

    /// Extracts the active page as text.
    async fn browser_read_page(
        &self,
        request: SessionRequest<ReadRequest>,
    ) -> TinyBusResult<DesktopResponse> {
        Ok(observing_reply(
            "browser-read-page",
            self.browser
                .read_page(&request.session, request.request)
                .await,
        ))
    }

    /// Evaluates JavaScript in the active page.
    async fn browser_evaluate(
        &self,
        request: SessionRequest<EvaluateRequest>,
    ) -> TinyBusResult<DesktopResponse> {
        Ok(browser_reply(
            "browser-evaluate",
            self.browser
                .evaluate(&request.session, request.request)
                .await,
        ))
    }

    /// Captures a screenshot and holds it for `BrowserReadOutput`.
    async fn browser_screenshot(
        &self,
        request: SessionRequest<BrowserScreenshotRequest>,
    ) -> TinyBusResult<DesktopResponse> {
        Ok(observing_reply(
            "browser-screenshot",
            self.browser
                .screenshot(&request.session, request.request)
                .await,
        ))
    }

    /// Reads one chunk of a held output.
    async fn browser_read_output(
        &self,
        request: ReadOutputRequest,
    ) -> TinyBusResult<DesktopResponse> {
        self.on_outputs(move |browser| {
            browser_reply(
                "browser-read-output",
                browser.read_output(&request.output, request.offset, request.max_len),
            )
        })
        .await
    }

    /// Releases a held output before it expires.
    async fn browser_release_output(
        &self,
        request: OutputRequest,
    ) -> TinyBusResult<DesktopResponse> {
        self.on_outputs(move |browser| {
            browser_reply(
                "browser-release-output",
                browser
                    .release_output(&request.output)
                    .map(|()| serde_json::json!({"output": request.output, "released": true})),
            )
        })
        .await
    }

    /// Lists a session's retained downloads.
    async fn browser_list_downloads(&self, request: SessionRef) -> TinyBusResult<DesktopResponse> {
        Ok(browser_reply(
            "browser-list-downloads",
            self.browser.list_downloads(&request.session).await,
        ))
    }

    /// Waits for a session's next download to finish.
    async fn browser_wait_download(
        &self,
        request: SessionRequest<DownloadWaitRequest>,
    ) -> TinyBusResult<DesktopResponse> {
        Ok(observing_reply(
            "browser-wait-download",
            self.browser
                .wait_download(&request.session, request.request)
                .await,
        ))
    }
}
